
help per page: 8

messages:

  help header: '&eHelp - &fPage <page>/<total>'
  help entry: '&e - &f<help>'
  help footer: '&e Use &c/help <next> &eto check out the next page'

  no page: '&cThere is no such page: <page>'

  no command: '&cUnknown command. Type /help to check out available commands.'

  custom /region: &region |
    /region claim - заприватить регион

  custom /rg: *region

  override /plugins: &plugins 'Plugins (1): &aMagic plugin'
  override /pl: *plugins

groups:
  player:
    permission: commands.default
    help: |
      Set home - &e/sethome
      Get starter kit - &e/kit start
      Change your password - &e/changepassword <old> <new> <new>
    commands: |
      register
      -reg
      login
      -l
      changepassword
      kit
      sethome

