
format:

  help-per-page: 8

  help-header: '&eHelp - &fPage <page>/<total>'
  help-entry: '&e - &f<help>'
  help-footer: '&e Use &c/help <next> &eto check out the next page'

  invalid-page-number: '&cThere is no such page: <page>'

  forbidden-command: '&cUnknown command. Type /help to check out available commands.'

# If you want to disable that, use custom-commands: {}
  custom-commands:
    plugins: &p 'Plugins (0): &aхаха а нет плагинов'
    pl: *p


groups:
  player:
    permission: commands.default
    help: |
      Set home - &e/sethome
      Get starter kit - &e/kit start
    commands: |
      register
      reg
      login
      l
      changepassword
      kit
      sethome

